apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-service
  template:
    metadata:
      labels:
        app: text-service
    spec:
      containers:
      - name: text-service
        image: text-service:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: text-service
spec:
  selector:
    app: text-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
